version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    reviewers:
      - "@biaw/dependencies"
