env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:

  # Possible Problems https://eslint.org/docs/rules/#possible-problems
  array-callback-return:
    - error
  no-duplicate-imports:
    - error
    - includeExports: true
  no-promise-executor-return:
    - error
  no-self-compare:
    - error
  no-template-curly-in-string:
    - error
  no-unreachable-loop:
    - error
  require-atomic-updates:
    - error

  # Suggestions https://eslint.org/docs/rules/#suggestions
  arrow-body-style:
    - error
  camelcase:
    - error
  capitalized-comments:
    - error
    - never
  complexity:
    - warn
  curly:
    - error
    - multi-line
  default-param-last:
    - error
  eqeqeq:
    - error
    - smart
  func-names:
    - error
    - never
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  max-lines:
    - error
  multiline-comment-style:
    - error
  new-cap:
    - error
  no-array-constructor:
    - error
  no-bitwise:
    - error
  no-caller:
    - error
  no-console:
    - error
  no-continue:
    - error
  no-else-return:
    - error
  no-empty-function:
    - error
  no-eq-null:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-implicit-coercion:
    - error
  no-invalid-this:
    - error
  no-lonely-if:
    - error
  no-loop-func:
    - error
  no-new:
    - error
  no-param-reassign:
    - error
  no-plusplus:
    - error
  no-proto:
    - error
  no-return-assign:
    - error
  no-return-await:
    - error
  no-underscore-dangle:
    - error
  no-unneeded-ternary:
    - error
  no-unused-expressions:
    - error
  no-useless-computed-key:
    - error
  no-useless-concat:
    - error
  no-useless-rename:
    - error
  no-useless-return:
    - error
  no-var:
    - error
  no-warning-comments:
    - warn
  operator-assignment:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-destructuring:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  quote-props:
    - error
    - as-needed
  radix:
    - error
    - as-needed
  require-await:
    - error
  sort-imports:
    - error
  spaced-comment:
    - error
  yoda:
    - error

  # Layout & Formatting https://eslint.org/docs/rules/#layout-formatting
  array-bracket-newline:
    - error
  array-bracket-spacing:
    - error
    - never
    - {
        singleValue: false,
        objectsInArrays: false,
        arraysInArrays: false,
      }
  array-element-newline:
    - error
    - consistent
    - multiline: true
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
  block-spacing:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
  comma-style:
    - error
  computed-property-spacing:
    - error
  dot-location:
    - error
    - property
  eol-last:
    - error
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
  implicit-arrow-linebreak:
    - error
  indent:
    - error
    - 2
  key-spacing:
    - error
    - mode: minimum
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - windows
  lines-around-comment:
    - error
  multiline-ternary:
    - error
    - always-multiline
  no-extra-parens:
    - error
  no-multi-spaces:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-tabs:
    - error
  no-trailing-spaces:
    - error
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
    - {
        multiline: true,
        consistent: true,
      }
  object-curly-spacing:
    - error
    - always
    - {
        objectsInObjects: false,
        arraysInObjects: false,
      }
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  operator-linebreak:
    - error
    - after
  quotes:
    - error
    - double
  rest-spread-spacing:
    - error
  semi:
    - error
  semi-spacing:
    - error
  semi-style:
    - error
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
    - {
        anonymous: never,
        named: never,
        asyncArrow: always,
      }
  space-in-parens:
    - error
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  switch-colon-spacing:
    - error
  template-curly-spacing:
    - error